//! Recursive-descent parser implementation for YARA rules.
//!
//! This module contains the core parser responsible for transforming
//! lexer tokens into a strongly-typed Abstract Syntax Tree (AST).
//!
//! Parsing is divided into specialized submodules for each major
//! section of a YARA rule:
//!
//! - [`condition`] parses condition expressions.
//! - [`expr`] provides expression parsing utilities.
//! - [`meta`] parses metadata entries.
//! - [`rule`] parses complete rule definitions.
//! - [`strings`] parses string declarations and modifiers.

/// Parsing of YARA condition expressions.
pub mod condition;

/// Shared expression parsing utilities.
pub mod expr;

/// Parsing of YARA metadata sections.
pub mod meta;

/// Parsing of complete YARA rule definitions.
pub mod rule;

/// Parsing of YARA string declarations and modifiers.
pub mod strings;

use crate::parser::{
    ast_parser::{meta::parse_meta, strings::parse_strings},
    syntax::{
        ConditionNode, ExprNode, MetaEntryNode, StringNode, rule::RuleNode, rule_file::RuleFileNode,
    },
    token::{Token, TokenType},
};

/// Recursive-descent parser for YARA rules.
///
/// `AstParser` consumes a stream of lexer tokens and produces
/// a strongly-typed Abstract Syntax Tree (AST) representing
/// the structure of a YARA rule.
///
/// The parser maintains a current position within the token
/// stream and provides helper methods for:
///
/// - Token inspection (`peek`, `check`)
/// - Token consumption (`advance`)
/// - Validation (`expect_*`)
/// - Expression parsing (`parse_or`, `parse_and`, etc.)
///
/// Parsing follows standard operator precedence rules:
///
/// ```text
/// or
/// └── and
///     └── comparison
///         └── primary
/// ```
///
/// This allows complex YARA conditions such as:
///
/// ```yara
/// filesize < 1MB and all of ($a*)
/// ```
///
/// to be represented as a nested AST.
pub struct AstParser {
    /// Complete token stream produced by the lexer.
    tokens: Vec<Token>,

    /// Current parser position.
    pos: usize,
}

impl AstParser {
    /// Creates a new parser instance.
    ///
    /// # Arguments
    ///
    /// * `tokens` (`Vec<Token>`) - Token stream generated by the lexer.
    ///
    /// # Returns
    ///
    /// Returns  new [`AstParser`] positioned at the start of the token stream.
    pub fn new(tokens: Vec<Token>) -> Self {
        Self { tokens, pos: 0 }
    }

    /// Checks whether the current token matches the provided token type.
    ///
    /// This function performs a lookahead without consuming the token.
    ///
    /// # Arguments
    ///
    /// * `token_type` (`&TokenType`) - Expected token type.
    ///
    /// # Returns
    ///
    /// Returns `true` if the current token matches, otherwise `false`.
    fn check(&self, token_type: &TokenType) -> bool {
        matches!(
            self.peek(),
            Some(Token { token_type: t, .. }) if t == token_type
        )
    }

    /// Returns the current token without consuming it.
    ///
    /// # Returns
    ///
    /// Returns the current token, or `None` if the end of the stream
    /// has been reached.
    fn peek(&self) -> Option<&Token> {
        self.tokens.get(self.pos)
    }

    /// Checks whether the current token is a keyword
    /// matching the specified value.
    ///
    /// # Arguments
    ///
    /// * `keyword` (`&str`) - Keyword to test against.
    ///
    /// # Returns
    ///
    /// Returns `true` if the current token is the requested keyword.
    fn peek_keyword(&self, keyword: &str) -> bool {
        matches!(
            self.peek(),
            Some(Token {
                token_type: TokenType::Keyword(k),
                ..
            }) if k == keyword
        )
    }

    /// Determines whether the current token is a YARA
    /// string identifier.
    ///
    /// Examples:
    ///
    /// ```yara
    /// $a
    /// $text
    /// $hex
    /// ```
    ///
    /// # Returns
    ///
    /// Returns `true` if the current token is a
    /// [`TokenType::StringIdentifier`].
    pub fn peek_string_identifier(&self) -> bool {
        matches!(
            self.peek(),
            Some(Token {
                token_type: TokenType::StringIdentifier(_),
                ..
            })
        )
    }

    /// Consumes and returns the current token.
    ///
    /// Advances the parser position by one.
    ///
    /// # Returns
    ///
    /// Returns the consumed token, or `None` if EOF has been reached.
    fn advance(&mut self) -> Option<&Token> {
        let tok = self.tokens.get(self.pos);
        self.pos += 1;
        tok
    }

    /// Consumes a token and verifies it matches the expected type.
    ///
    /// # Arguments
    ///
    /// * `expected` (`&TokenType`) - Token type that must be present.
    ///
    /// # Returns
    /// 
    /// Returns `Ok(())` if the next token is of the expected type
    /// 
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token does not match
    /// - the current token is `None`
    /// the expected type.
    fn expect(&mut self, expected: &TokenType) -> Result<(), String> {
        match self.peek() {
            Some(t) if &t.token_type == expected => {
                self.advance();
                Ok(())
            }
            Some(t) => Err(format!("Expected {:?}, found {:?}", expected, t.token_type)),
            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a numeric token.
    ///
    /// # Returns
    ///
    /// The numeric value exactly as represented in the source.
    ///
    /// Examples:
    ///
    /// ```yara
    /// 100
    /// 0x5A4D
    /// 500KB
    /// ```
    /// 
    /// # Errors
    /// 
    /// Returns an error if:
    /// - the current token is not of type `TokenType::Number`
    /// - the current token is `None`
    fn expect_number(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Number(num),
                ..
            }) => Ok(num.clone()),
            Some(token) => Err(format!("Expected Number, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a boolean keyword.
    ///
    /// Supported values:
    ///
    /// ```yara
    /// true
    /// false
    /// ```
    ///
    /// # Returns
    ///
    /// The corresponding Rust boolean value.
    /// 
    /// # Errors 
    /// 
    /// Returns an error if:
    /// - the token is `None`
    /// - the token is not of `TokenType::Keyword`
    /// - the token is a keyword not equal to either `true` or `false`
    fn expect_boolean(&mut self) -> Result<bool, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Keyword(bool_val),
                ..
            }) => match bool_val.as_str() {
                "true" => Ok(true),
                "false" => Ok(false),
                _ => Err(format!("Expected boolean, found keyword '{}'", bool_val)),
            },

            Some(token) => Err(format!("Expected boolean, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a standard identifier.
    ///
    /// Examples:
    ///
    /// ```yara
    /// filesize
    /// pe
    /// imphash
    /// ```
    ///
    /// # Returns
    ///
    /// Return the identifier name
    /// 
    /// # Errors
    /// 
    /// Returns an error if:
    /// - the current token is not of `TokenType::Identifier`
    /// - the current token is `None`
    fn expect_identifier(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Identifier(name),
                ..
            }) => Ok(name.clone()),

            Some(token) => Err(format!("Expected identifier, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a string literal
    ///
    /// # Returns
    ///
    /// Returns the string literal
    /// 
    /// # Errors
    /// 
    /// Returns an error if:
    /// - current token is not of `TokenType::StringLiteral`
    /// - current token is `None`
    fn expect_string_literal(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::StringLiteral(name),
                ..
            }) => Ok(name.clone()),
            Some(token) => Err(format!(
                "Expected StringLiteral, found {:?}",
                token.token_type
            )),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a standard identifier.
    ///
    /// Examples:
    ///
    /// ```yara
    /// filesize
    /// pe
    /// imphash
    /// ```
    ///
    /// # Returns
    ///
    /// Returns the identifier name.
    /// 
    /// # Errors
    /// 
    /// Returns an error if:
    /// - the current token is not of `TokenType::StringIdentifier`
    /// - the current token is `None`
    fn expect_string_identifier(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::StringIdentifier(name),
                ..
            }) => Ok(name.clone()),

            Some(token) => Err(format!(
                "Expected string identifier, found {:?}",
                token.token_type
            )),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a specific keyword.
    ///
    /// # Arguments
    ///
    /// * `keyword` (`&str`) - Expected keyword value.
    /// 
    /// # Returns
    /// 
    /// Returns `Ok(())` if the current toke is the requested keyword
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token is not the requested keyword.
    fn expect_keyword(&mut self, keyword: &str) -> Result<(), String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Keyword(found),
                ..
            }) if found == keyword => Ok(()),

            Some(token) => Err(format!(
                "Expected keyword '{}', found {:?}",
                keyword, token.token_type
            )),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes any keyword token.
    /// 
    /// Examples:
    ///
    /// ```yara
    /// wide
    /// ascii
    /// nocase
    /// ```
    ///
    /// # Returns
    ///
    /// The keyword value that was consumed.
    /// 
    /// # Errors
    /// 
    /// Returns an error if:
    /// - the current token is not of `TokenType::Keyword`
    /// - the current token is `None`
    pub fn expect_any_keyword(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Keyword(keyword),
                ..
            }) => Ok(keyword.clone()),

            Some(token) => Err(format!("Expected keyword, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Parses a complete YARA rule.
    ///
    /// This is the parser entry point.
    ///
    /// Supported sections:
    ///
    /// - `meta:`
    /// - `strings:`
    /// - `condition:`
    ///
    /// Example:
    ///
    /// ```yara
    /// rule Example {
    ///     meta:
    ///         author = "mints"
    ///
    ///     strings:
    ///         $a = "hello"
    ///
    ///     condition:
    ///         $a
    /// }
    /// ```
    /// 
    /// # Arguments
    /// 
    /// * `parser` (`&mut AstParser`) - an AstParser positioned at the beginning of
    ///  a YARA rule
    ///
    /// # Returns
    ///
    /// A fully populated [`RuleNode`] representing the rule.
    /// 
    /// ## Errors
    /// 
    /// Returns an error if:
    /// - The rule is malformed
    fn parse_rule(parser: &mut AstParser) -> Result<RuleNode, String> {
        parser.expect_keyword("rule")?;
        // Debug
        //println!("matched rule keyword");

        let name = parser.expect_identifier()?;
        println!("Parsed rule name: {}", name);
        // TODO: tags

        parser.expect(&TokenType::LBrace)?;
        let mut meta: Vec<MetaEntryNode> = Vec::new();
        let mut strings: Vec<StringNode> = Vec::new();
        let mut condition: ConditionNode = ConditionNode {
            expression: ExprNode::Identifier(String::new()),
        };
        if parser.peek_keyword("meta") {
            parser.expect_keyword("meta")?;
            parser.expect(&TokenType::Colon)?;
            meta = parse_meta(parser)?;
        }
        if parser.peek_keyword("strings") {
            parser.expect_keyword("strings")?;
            parser.expect(&TokenType::Colon)?;
            strings = parse_strings(parser)?;
        }
        if parser.peek_keyword("condition") {
            parser.expect_keyword("condition")?;
            parser.expect(&TokenType::Colon)?;
            condition = condition::parse_condition(parser)?;
        }

        parser.expect(&TokenType::RBrace)?;

        Ok(RuleNode {
            name,
            is_global: false,
            is_private: false,
            tags: Vec::new(),
            meta,
            strings,
            condition,
        })
    }

    /// Parses a full YARA file into a list of rules.
    ///
    /// This function handles:
    /// - import statements
    /// - multiple rule definitions
    ///
    /// The parser consumes tokens sequentially and delegates
    /// rule parsing to [`AstParser::parse_rule`].
    /// 
    /// # Arguments
    /// 
    /// * `parser` (`AstParser`) - an `AstParser` positioned at the beginning of a
    /// YARA file
    /// 
    /// # Errors
    /// 
    /// Returns an error if:
    /// - The YARA file or any of its rules is malformed
    pub fn parse_rule_file(mut parser: AstParser) -> Result<RuleFileNode, String> {
        let mut imports: Vec<String> = Vec::new();
        while parser.peek_keyword("import") {
            parser.expect_keyword("import")?;
            imports.push(parser.expect_string_literal()?);
        }
        let mut rules: Vec<RuleNode> = Vec::new();
        while parser.peek_keyword("rule") {
            rules.push(Self::parse_rule(&mut parser)?);
        }
        Ok(RuleFileNode { imports, rules })
    }
}
