//! Recursive-descent parser implementation for YARA rules.
//!
//! This module contains the core parser responsible for transforming
//! lexer tokens into a strongly-typed Abstract Syntax Tree (AST).
//!
//! Parsing is divided into specialized submodules for each major
//! section of a YARA rule:
//!
//! - [`condition`] parses condition expressions.
//! - [`expr`] provides expression parsing utilities.
//! - [`meta`] parses metadata entries.
//! - [`rule`] parses complete rule definitions.
//! - [`strings`] parses string declarations and modifiers.

/// Parsing of YARA condition expressions.
pub mod condition;

pub mod hex;

/// Parsing of YARA metadata sections.
pub mod meta;

/// Parsing of YARA string declarations and modifiers.
pub mod strings;

use crate::parser::{
    ast_parser::{meta::parse_meta, strings::parse_strings},
    syntax::{
        ConditionNode, ExprNode, MetaEntryNode, StringNode, rule::RuleNode, rule_file::RuleFileNode,
    },
    token::{Token, TokenType},
};

/// Recursive-descent parser for YARA rules.
///
/// `AstParser` consumes a stream of lexer tokens and produces
/// a strongly-typed Abstract Syntax Tree (AST) representing
/// the structure of a YARA rule.
///
/// The parser maintains a current position within the token
/// stream and provides helper methods for:
///
/// - Token inspection (`peek`, `check`)
/// - Token consumption (`advance`)
/// - Validation (`expect_*`)
/// - Expression parsing (`parse_or`, `parse_and`, etc.)
///
/// Parsing follows standard operator precedence rules:
///
/// ```text
/// or
/// └── and
///     └── comparison
///         └── primary
/// ```
///
/// This allows complex YARA conditions such as:
///
/// ```yara
/// filesize < 1MB and all of ($a*)
/// ```
///
/// to be represented as a nested AST.
pub struct AstParser {
    /// Complete token stream produced by the lexer.
    tokens: Vec<Token>,

    /// Current parser position.
    pos: usize,
}

impl AstParser {
    /// Creates a new parser instance.
    ///
    /// # Arguments
    ///
    /// * `tokens` (`Vec<Token>`) - Token stream generated by the lexer.
    ///
    /// # Returns
    ///
    /// Returns  new [`AstParser`] positioned at the start of the token stream.
    pub fn new(tokens: Vec<Token>) -> Self {
        Self { tokens, pos: 0 }
    }

    /// Checks whether the current token matches the provided token type.
    ///
    /// This function performs a lookahead without consuming the token.
    ///
    /// # Arguments
    ///
    /// * `token_type` (`&TokenType`) - Expected token type.
    ///
    /// # Returns
    ///
    /// Returns `true` if the current token matches, otherwise `false`.
    fn check(&self, token_type: &TokenType) -> bool {
        matches!(
            self.peek(),
            Some(Token { token_type: t, .. }) if t == token_type
        )
    }

    /// Returns the current token without consuming it.
    ///
    /// # Returns
    ///
    /// Returns the current token, or `None` if the end of the stream
    /// has been reached.
    fn peek(&self) -> Option<&Token> {
        self.tokens.get(self.pos)
    }

    /// Checks whether the current token is a keyword
    /// matching the specified value.
    ///
    /// # Arguments
    ///
    /// * `keyword` (`&str`) - Keyword to test against.
    ///
    /// # Returns
    ///
    /// Returns `true` if the current token is the requested keyword.
    fn peek_keyword(&self, keyword: &str) -> bool {
        matches!(
            self.peek(),
            Some(Token {
                token_type: TokenType::Keyword(k),
                ..
            }) if k == keyword
        )
    }

    /// Determines whether the current token is a YARA
    /// string identifier.
    ///
    /// Examples:
    ///
    /// ```yara
    /// $a
    /// $text
    /// $hex
    /// ```
    ///
    /// # Returns
    ///
    /// Returns `true` if the current token is a
    /// [`TokenType::StringIdentifier`].
    pub fn peek_string_identifier(&self) -> bool {
        matches!(
            self.peek(),
            Some(Token {
                token_type: TokenType::StringIdentifier(_),
                ..
            })
        )
    }

    /// Consumes and returns the current token.
    ///
    /// Advances the parser position by one.
    ///
    /// # Returns
    ///
    /// Returns the consumed token, or `None` if EOF has been reached.
    fn advance(&mut self) -> Option<&Token> {
        let tok = self.tokens.get(self.pos);
        self.pos += 1;
        tok
    }

    /// Consumes a token and verifies it matches the expected type.
    ///
    /// # Arguments
    ///
    /// * `expected` (`&TokenType`) - Token type that must be present.
    ///
    /// # Returns
    ///
    /// Returns `Ok(())` if the next token is of the expected type
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token does not match
    /// - the current token is `None`
    ///   the expected type.
    fn expect(&mut self, expected: &TokenType) -> Result<(), String> {
        match self.peek() {
            Some(t) if &t.token_type == expected => {
                self.advance();
                Ok(())
            }
            Some(t) => Err(format!("Expected {:?}, found {:?}", expected, t.token_type)),
            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a numeric token.
    ///
    /// # Returns
    ///
    /// The numeric value exactly as represented in the source.
    ///
    /// Examples:
    ///
    /// ```yara
    /// 100
    /// 0x5A4D
    /// 500KB
    /// ```
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token is not of type `TokenType::Number`
    /// - the current token is `None`
    fn expect_number(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Number(num),
                ..
            }) => Ok(num.clone()),
            Some(token) => Err(format!("Expected Number, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a boolean keyword.
    ///
    /// Supported values:
    ///
    /// ```yara
    /// true
    /// false
    /// ```
    ///
    /// # Returns
    ///
    /// The corresponding Rust boolean value.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the token is `None`
    /// - the token is not of `TokenType::Keyword`
    /// - the token is a keyword not equal to either `true` or `false`
    fn expect_boolean(&mut self) -> Result<bool, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Keyword(bool_val),
                ..
            }) => match bool_val.as_str() {
                "true" => Ok(true),
                "false" => Ok(false),
                _ => Err(format!("Expected boolean, found keyword '{}'", bool_val)),
            },

            Some(token) => Err(format!("Expected boolean, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a standard identifier.
    ///
    /// Examples:
    ///
    /// ```yara
    /// filesize
    /// pe
    /// imphash
    /// ```
    ///
    /// # Returns
    ///
    /// Return the identifier name
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token is not of `TokenType::Identifier`
    /// - the current token is `None`
    fn expect_identifier(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Identifier(name),
                ..
            }) => Ok(name.clone()),

            Some(token) => Err(format!("Expected identifier, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a string literal
    ///
    /// # Returns
    ///
    /// Returns the string literal
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - current token is not of `TokenType::StringLiteral`
    /// - current token is `None`
    fn expect_string_literal(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::StringLiteral(name),
                ..
            }) => Ok(name.clone()),
            Some(token) => Err(format!(
                "Expected StringLiteral, found {:?}",
                token.token_type
            )),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a YARA hex string
    ///
    /// # Returns
    ///
    /// Returns a [`TokenType::HexString`]
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - current token is not of `TokenType::HexString`
    /// - current token is `None`
    fn expect_hex_string(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::HexString(name),
                ..
            }) => Ok(name.clone()),
            Some(token) => Err(format!("Expected HexString, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a YARA Regular Expression String
    ///
    /// # Returns
    ///
    /// Returns a ['TokenType::Regex`]
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - current token is not of `TokenType::Regex`
    /// - current token is `None`
    fn expect_regex(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Regex(name),
                ..
            }) => Ok(name.clone()),
            Some(token) => Err(format!("Expected Regex, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a standard identifier.
    ///
    /// Examples:
    ///
    /// ```yara
    /// filesize
    /// pe
    /// imphash
    /// ```
    ///
    /// # Returns
    ///
    /// Returns the identifier name.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token is not of `TokenType::StringIdentifier`
    /// - the current token is `None`
    fn expect_string_identifier(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::StringIdentifier(name),
                ..
            }) => Ok(name.clone()),

            Some(token) => Err(format!(
                "Expected string identifier, found {:?}",
                token.token_type
            )),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes a specific keyword.
    ///
    /// # Arguments
    ///
    /// * `keyword` (`&str`) - Expected keyword value.
    ///
    /// # Returns
    ///
    /// Returns `Ok(())` if the current toke is the requested keyword
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token is not the requested keyword.
    fn expect_keyword(&mut self, keyword: &str) -> Result<(), String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Keyword(found),
                ..
            }) if found == keyword => Ok(()),

            Some(token) => Err(format!(
                "Expected keyword '{}', found {:?}",
                keyword, token.token_type
            )),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes any keyword token.
    ///
    /// Examples:
    ///
    /// ```yara
    /// wide
    /// ascii
    /// nocase
    /// ```
    ///
    /// # Returns
    ///
    /// The keyword value that was consumed.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - the current token is not of `TokenType::Keyword`
    /// - the current token is `None`
    pub fn expect_any_keyword(&mut self) -> Result<String, String> {
        match self.advance() {
            Some(Token {
                token_type: TokenType::Keyword(keyword),
                ..
            }) => Ok(keyword.clone()),

            Some(token) => Err(format!("Expected keyword, found {:?}", token.token_type)),

            None => Err("Unexpected EOF".into()),
        }
    }

    /// Consumes the tokens needed to create a rule name
    ///
    /// This is to prevent errors from occurring when unexpected
    /// characters show up in a rule name, such as a dash (`-`)
    fn expect_rule_name(&mut self) -> Result<String, String> {
        let mut name = String::new();

        while !self.check(&TokenType::LBrace) {
            let token = self
                .advance()
                .ok_or("Unexpected EOF while parsing rule name")?;

            match &token.token_type {
                TokenType::Identifier(s) => name.push_str(s),
                TokenType::Minus => name.push('-'),
                _ => {
                    return Err(format!(
                        "Unexpected token in rule name: {:?}",
                        token.token_type
                    ));
                }
            }
        }
        Ok(name)
    }

    /// Parses a complete YARA rule.
    ///
    /// This is the parser entry point.
    ///
    /// Supported sections:
    ///
    /// - `meta:`
    /// - `strings:`
    /// - `condition:`
    ///
    /// Example:
    ///
    /// ```yara
    /// rule Example {
    ///     meta:
    ///         author = "mints"
    ///
    ///     strings:
    ///         $a = "hello"
    ///
    ///     condition:
    ///         $a
    /// }
    /// ```
    ///
    /// # Arguments
    ///
    /// * `parser` (`&mut AstParser`) - an AstParser positioned at the beginning of
    ///   a YARA rule
    ///
    /// # Returns
    ///
    /// A fully populated [`RuleNode`] representing the rule.
    ///
    /// ## Errors
    ///
    /// Returns an error if:
    /// - The rule is malformed
    fn parse_rule(parser: &mut AstParser) -> Result<RuleNode, String> {
        parser.expect_keyword("rule")?;

        let name = parser.expect_rule_name()?;
        // TODO: tags

        parser.expect(&TokenType::LBrace)?;
        let mut meta: Vec<MetaEntryNode> = Vec::new();
        let mut strings: Vec<StringNode> = Vec::new();
        let mut condition: ConditionNode = ConditionNode {
            expression: ExprNode::Identifier(String::new()),
        };
        if parser.peek_keyword("meta") {
            parser.expect_keyword("meta")?;
            parser.expect(&TokenType::Colon)?;
            meta = parse_meta(parser)?;
        }
        if parser.peek_keyword("strings") {
            parser.expect_keyword("strings")?;
            parser.expect(&TokenType::Colon)?;
            strings = parse_strings(parser)?;
        }
        if parser.peek_keyword("condition") {
            parser.expect_keyword("condition")?;
            parser.expect(&TokenType::Colon)?;
            condition = condition::parse_condition(parser)?;
        }

        parser.expect(&TokenType::RBrace)?;

        Ok(RuleNode {
            name,
            is_global: false,
            is_private: false,
            tags: Vec::new(),
            meta,
            strings,
            condition,
        })
    }

    /// Parses a full YARA file into a list of rules.
    ///
    /// This function handles:
    /// - import statements
    /// - multiple rule definitions
    ///
    /// The parser consumes tokens sequentially and delegates
    /// rule parsing to [`AstParser::parse_rule`].
    ///
    /// # Arguments
    ///
    /// * `parser` (`AstParser`) - an `AstParser` positioned at the beginning of a
    ///   YARA file
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The YARA file or any of its rules is malformed
    pub fn parse_rule_file(mut parser: AstParser) -> Result<RuleFileNode, String> {
        let mut imports: Vec<String> = Vec::new();
        while parser.peek_keyword("import") {
            parser.expect_keyword("import")?;
            imports.push(parser.expect_string_literal()?);
        }
        let mut rules: Vec<RuleNode> = Vec::new();
        while parser.peek_keyword("rule") {
            rules.push(Self::parse_rule(&mut parser)?);
        }
        Ok(RuleFileNode { imports, rules })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::{
        span::Span,
        token::{Token, TokenType},
    };

    fn make_token(token_type: TokenType) -> Token {
        Token {
            token_type,
            span: Span { line: 1, column: 1 },
        }
    }

    fn make_parser(types: Vec<TokenType>) -> AstParser {
        AstParser::new(types.into_iter().map(make_token).collect())
    }

    // --- peek ---

    #[test]
    fn peek_returns_current_token_without_consuming() {
        let parser = make_parser(vec![TokenType::LBrace]);

        let _ = parser.peek();
        let _ = parser.peek();

        assert_eq!(parser.pos, 0);
    }

    #[test]
    fn peek_returns_none_on_empty_stream() {
        let parser = make_parser(vec![]);

        assert!(parser.peek().is_none());
    }

    // --- check ---

    #[test]
    fn check_returns_true_when_token_matches() {
        let parser = make_parser(vec![TokenType::LBrace]);

        assert!(parser.check(&TokenType::LBrace));
    }

    #[test]
    fn check_returns_false_when_token_does_not_match() {
        let parser = make_parser(vec![TokenType::RBrace]);

        assert!(!parser.check(&TokenType::LBrace));
    }

    #[test]
    fn check_returns_false_on_empty_stream() {
        let parser = make_parser(vec![]);

        assert!(!parser.check(&TokenType::LBrace));
    }

    // --- peek_keyword ---

    #[test]
    fn peek_keyword_returns_true_when_keyword_matches() {
        let parser = make_parser(vec![TokenType::Keyword("rule".to_string())]);

        assert!(parser.peek_keyword("rule"));
    }

    #[test]
    fn peek_keyword_returns_false_when_keyword_differs() {
        let parser = make_parser(vec![TokenType::Keyword("condition".to_string())]);

        assert!(!parser.peek_keyword("rule"));
    }

    #[test]
    fn peek_keyword_returns_false_when_token_is_not_keyword() {
        let parser = make_parser(vec![TokenType::Identifier("rule".to_string())]);

        assert!(!parser.peek_keyword("rule"));
    }

    // --- peek_string_identifier ---

    #[test]
    fn peek_string_identifier_returns_true_for_string_identifier() {
        let parser = make_parser(vec![TokenType::StringIdentifier("$foo".to_string())]);

        assert!(parser.peek_string_identifier());
    }

    #[test]
    fn peek_string_identifier_returns_false_for_identifier() {
        let parser = make_parser(vec![TokenType::Identifier("foo".to_string())]);

        assert!(!parser.peek_string_identifier());
    }

    // --- advance ---

    #[test]
    fn advance_consumes_and_returns_current_token() {
        let mut parser = make_parser(vec![TokenType::LBrace]);

        let token = parser.advance();

        assert!(token.is_some());
        assert_eq!(parser.pos, 1);
    }

    #[test]
    fn advance_returns_none_at_end_of_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.advance().is_none());
    }

    #[test]
    fn advance_moves_through_tokens_in_order() {
        let mut parser = make_parser(vec![TokenType::LBrace, TokenType::RBrace]);

        let first = parser.advance().unwrap().token_type.clone();
        let second = parser.advance().unwrap().token_type.clone();

        assert_eq!(first, TokenType::LBrace);
        assert_eq!(second, TokenType::RBrace);
    }

    // --- expect ---

    #[test]
    fn expect_succeeds_and_consumes_when_token_matches() {
        let mut parser = make_parser(vec![TokenType::LBrace]);

        let result = parser.expect(&TokenType::LBrace);

        assert!(result.is_ok());
        assert_eq!(parser.pos, 1);
    }

    #[test]
    fn expect_returns_err_when_token_does_not_match() {
        let mut parser = make_parser(vec![TokenType::RBrace]);

        let result = parser.expect(&TokenType::LBrace);

        assert!(result.is_err());
    }

    #[test]
    fn expect_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        let result = parser.expect(&TokenType::LBrace);

        assert!(result.is_err());
    }

    // --- expect_number ---

    #[test]
    fn expect_number_returns_value_on_number_token() {
        let mut parser = make_parser(vec![TokenType::Number("42".to_string())]);

        let result = parser.expect_number();

        assert_eq!(result, Ok("42".to_string()));
    }

    #[test]
    fn expect_number_returns_err_on_non_number_token() {
        let mut parser = make_parser(vec![TokenType::Identifier("foo".to_string())]);

        assert!(parser.expect_number().is_err());
    }

    #[test]
    fn expect_number_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_number().is_err());
    }

    // --- expect_boolean ---

    #[test]
    fn expect_boolean_returns_true_for_true_keyword() {
        let mut parser = make_parser(vec![TokenType::Keyword("true".to_string())]);

        assert_eq!(parser.expect_boolean(), Ok(true));
    }

    #[test]
    fn expect_boolean_returns_false_for_false_keyword() {
        let mut parser = make_parser(vec![TokenType::Keyword("false".to_string())]);

        assert_eq!(parser.expect_boolean(), Ok(false));
    }

    #[test]
    fn expect_boolean_returns_err_for_non_boolean_keyword() {
        let mut parser = make_parser(vec![TokenType::Keyword("rule".to_string())]);

        assert!(parser.expect_boolean().is_err());
    }

    #[test]
    fn expect_boolean_returns_err_for_non_keyword_token() {
        let mut parser = make_parser(vec![TokenType::Identifier("true".to_string())]);

        assert!(parser.expect_boolean().is_err());
    }

    #[test]
    fn expect_boolean_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_boolean().is_err());
    }

    // --- expect_identifier ---

    #[test]
    fn expect_identifier_returns_name_on_identifier_token() {
        let mut parser = make_parser(vec![TokenType::Identifier("foo".to_string())]);

        assert_eq!(parser.expect_identifier(), Ok("foo".to_string()));
    }

    #[test]
    fn expect_identifier_returns_err_on_keyword_token() {
        let mut parser = make_parser(vec![TokenType::Keyword("rule".to_string())]);

        assert!(parser.expect_identifier().is_err());
    }

    #[test]
    fn expect_identifier_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_identifier().is_err());
    }

    // --- expect_string_literal ---

    #[test]
    fn expect_string_literal_returns_value_on_string_literal_token() {
        let mut parser = make_parser(vec![TokenType::StringLiteral("cmd.exe".to_string())]);

        assert_eq!(parser.expect_string_literal(), Ok("cmd.exe".to_string()));
    }

    #[test]
    fn expect_string_literal_returns_err_on_identifier_token() {
        let mut parser = make_parser(vec![TokenType::Identifier("foo".to_string())]);

        assert!(parser.expect_string_literal().is_err());
    }

    #[test]
    fn expect_string_literal_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_string_literal().is_err());
    }

    // --- expect_string_identifier ---

    #[test]
    fn expect_string_identifier_returns_value_on_string_identifier_token() {
        let mut parser = make_parser(vec![TokenType::StringIdentifier("$foo".to_string())]);

        assert_eq!(parser.expect_string_identifier(), Ok("$foo".to_string()));
    }

    #[test]
    fn expect_string_identifier_returns_err_on_identifier_token() {
        let mut parser = make_parser(vec![TokenType::Identifier("foo".to_string())]);

        assert!(parser.expect_string_identifier().is_err());
    }

    #[test]
    fn expect_string_identifier_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_string_identifier().is_err());
    }

    // --- expect_keyword ---

    #[test]
    fn expect_keyword_succeeds_when_keyword_matches() {
        let mut parser = make_parser(vec![TokenType::Keyword("rule".to_string())]);

        assert!(parser.expect_keyword("rule").is_ok());
    }

    #[test]
    fn expect_keyword_returns_err_when_keyword_differs() {
        let mut parser = make_parser(vec![TokenType::Keyword("condition".to_string())]);

        assert!(parser.expect_keyword("rule").is_err());
    }

    #[test]
    fn expect_keyword_returns_err_on_non_keyword_token() {
        let mut parser = make_parser(vec![TokenType::Identifier("rule".to_string())]);

        assert!(parser.expect_keyword("rule").is_err());
    }

    #[test]
    fn expect_keyword_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_keyword("rule").is_err());
    }

    // --- expect_any_keyword ---

    #[test]
    fn expect_any_keyword_returns_keyword_value() {
        let mut parser = make_parser(vec![TokenType::Keyword("wide".to_string())]);

        assert_eq!(parser.expect_any_keyword(), Ok("wide".to_string()));
    }

    #[test]
    fn expect_any_keyword_returns_err_on_non_keyword_token() {
        let mut parser = make_parser(vec![TokenType::Identifier("wide".to_string())]);

        assert!(parser.expect_any_keyword().is_err());
    }

    #[test]
    fn expect_any_keyword_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_any_keyword().is_err());
    }

    // --- expect_rule_name ---

    #[test]
    fn expect_rule_name_parses_simple_name() {
        let mut parser = make_parser(vec![
            TokenType::Identifier("my_rule".to_string()),
            TokenType::LBrace,
        ]);

        assert_eq!(parser.expect_rule_name(), Ok("my_rule".to_string()));
    }

    #[test]
    fn expect_rule_name_parses_name_with_dash() {
        let mut parser = make_parser(vec![
            TokenType::Identifier("my".to_string()),
            TokenType::Minus,
            TokenType::Identifier("rule".to_string()),
            TokenType::LBrace,
        ]);

        assert_eq!(parser.expect_rule_name(), Ok("my-rule".to_string()));
    }

    #[test]
    fn expect_rule_name_returns_err_on_unexpected_token_in_name() {
        let mut parser = make_parser(vec![TokenType::LParen, TokenType::LBrace]);

        assert!(parser.expect_rule_name().is_err());
    }

    #[test]
    fn expect_rule_name_returns_err_on_empty_stream() {
        let mut parser = make_parser(vec![]);

        assert!(parser.expect_rule_name().is_err());
    }
}
